image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pwd
          - ls -al

    - step:
        name: Deploy to Build
        caches:
          - node
        script:
          # - npm install @angular/cli@~7.3.9 && ng build --prod
          # - npm install && npm run build
          - npm install
          - npm install -g @angular/cli
          - ng build --prod
          # - echo "$(ls -la dist/)"
          # - scp -r dist/ user@34.73.227.137:/projets/commerce1
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: production
        caches:
          - node
        # trigger:
        script:
          - npm install -g firebase-tools
          # - npm install
          # - ng build
          - firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project $FIREBASE_PROJECT --public dist