image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pwd
          - ls -al

    - step:
        name: Deploy to Build
        caches:
          - node
        script:
          - npm install && npm run build
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: production
        caches:
          - node
        # trigger:
        script:
          - npm install -g firebase-tools
          - npm install
          - ng build
          - firebase deploy --only hosting --token "$FIREBASE_TOKEN" --public dist
          # - firebase deploy --only hosting --token=$FIREBASE_TOKEN --project portfolio --non-interactive
        # script:
        #    - pipe: atlassian/firebase-deploy:0.2.4 --only hosting
        #      variables:
        #        FIREBASE_TOKEN: $FIREBASE_TOKEN
        #        PROJECT_ID: $FIREBASE_PROJECT
