image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pwd
          - ls -al

    - step:
        name: Deploy to Build
        caches:
          - node
        script:
          - npm install @angular/cli@~7.3.9
          - npm install && npm run build
          - ng build --prod
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: production
        caches:
          - node
        # trigger:
        script:
          - npm install -g firebase-tools
          # - npm install
          # - ng build
          - firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project $FIREBASE_PROJECT --public dist